# Generated by Django 4.1.5 on 2023-01-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='issue_date',
            field=models.DateField(max_length=10),
        ),
    ]
